import { useState } from 'react';
import { ArrowUp, Bot, Check, Database, Lightbulb, RotateCcw, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { useAskInstagramAgent } from '@workspace/api-client-react';
import type { AgentResponse, InstagramAnalysis } from '@workspace/api-client-react';

type Message = { id: string; role: 'user' | 'assistant'; text: string; response?: AgentResponse };
const prompts = ['What should I post more of?', 'Why did my reach dip?', 'Find my best posting pattern'];

export default function Assistant({ analysis }: { analysis: InstagramAnalysis | null }) {
  const agent = useAskInstagramAgent();
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [lastQuestion, setLastQuestion] = useState('');
  const ask = (value = question) => {
    if (!analysis || !value.trim() || agent.isPending) return;
    const clean = value.trim();
    setQuestion('');
    setLastQuestion(clean);
    setMessages((current) => [...current, { id: `user-${Date.now()}`, role: 'user', text: clean }]);
    agent.mutate({ data: { question: clean, analysis } }, { onSuccess: (response) => setMessages((current) => [...current, { id: `assistant-${Date.now()}`, role: 'assistant', text: response.answer, response }]) });
  };
  if (!analysis) return <div className="mx-auto max-w-3xl py-12 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-accent text-accent-foreground"><Bot size={25} /></div><h1 className="mt-5 font-display text-3xl font-semibold tracking-tight">Give the assistant something to work with.</h1><p className="mx-auto mt-3 max-w-md text-sm leading-relaxed text-muted-foreground">Load your Instagram analysis and ask questions in plain language. The assistant cites your own numbers as it goes.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground" data-testid="link-assistant-load-data">Load an analysis</Link></div>;
  return <div className="mx-auto grid max-w-[1160px] gap-6 lg:grid-cols-[1fr_300px]">
    <section className="flex min-h-[650px] flex-col rounded-3xl border border-card-border bg-card shadow-[0_8px_24px_hsl(var(--foreground)/.035)]">
      <div className="flex items-center gap-3 border-b border-border/70 px-5 py-5 md:px-7"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent text-accent-foreground"><Bot size={20} /></div><div><div className="font-display text-lg font-semibold">Signal assistant</div><div className="flex items-center gap-1.5 text-xs text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-accent" /> Grounded in {analysis.accountName}</div></div><div className="ml-auto hidden rounded-lg bg-secondary px-2.5 py-1.5 font-mono-ui text-[9px] uppercase tracking-wider text-muted-foreground sm:block">Tool-using AI</div></div>
      <div className="flex-1 space-y-5 overflow-auto px-5 py-7 md:px-9">{messages.length === 0 && <div className="mx-auto max-w-md py-10 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Sparkles size={21} /></div><h1 className="mt-5 font-display text-2xl font-semibold">Ask better questions.</h1><p className="mt-2 text-sm leading-relaxed text-muted-foreground">I’ve read your recent posts, formats, and trends. Ask me to spot a pattern or make a call.</p><div className="mt-7 flex flex-wrap justify-center gap-2">{prompts.map((prompt) => <button type="button" key={prompt} onClick={() => ask(prompt)} className="rounded-full border border-border px-3 py-2 text-xs font-medium hover:border-primary/45 hover:bg-primary/5" data-testid={`button-prompt-${prompts.indexOf(prompt)}`}>{prompt}</button>)}</div></div>}{messages.map((message) => <div key={message.id} className={`flex gap-3 ${message.role === 'user' ? 'justify-end' : 'justify-start'}`} data-testid={`message-${message.role}-${message.id}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${message.role === 'user' ? 'rounded-br-sm bg-primary text-primary-foreground' : 'rounded-bl-sm bg-secondary text-secondary-foreground'}`}>{message.text}{message.response && <div className="mt-4 space-y-3 border-t border-secondary-foreground/10 pt-3"><div className="flex flex-wrap gap-1.5">{message.response.tools.map((tool) => <span key={tool} className="inline-flex items-center gap-1 rounded-md bg-card/70 px-2 py-1 font-mono-ui text-[9px] text-muted-foreground"><Database size={10} />{tool}</span>)}</div>{message.response.citations.length > 0 && <div className="text-[10px] text-muted-foreground">Based on: {message.response.citations.join(' · ')}</div>}</div>}</div></div>)}{agent.isPending && <div className="flex gap-3"><div className="rounded-2xl rounded-bl-sm bg-secondary px-4 py-4"><div className="flex gap-1"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-accent" /><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-accent [animation-delay:100ms]" /><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-accent [animation-delay:200ms]" /></div></div></div>}{agent.isError && <div className="flex items-center gap-2 rounded-xl bg-primary/10 px-3 py-2 text-xs text-primary" data-testid="status-assistant-error"><span>That answer did not come through.</span><button type="button" onClick={() => ask(lastQuestion)} className="inline-flex items-center gap-1 font-semibold underline" data-testid="button-retry-assistant"><RotateCcw size={12} /> Retry</button></div>}</div>
      <div className="border-t border-border/70 p-4 md:p-5"><div className="flex items-end gap-2 rounded-2xl border border-border bg-background p-2 transition-colors focus-within:border-primary/60"><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); ask(); } }} placeholder="Ask about your content, reach, or next move…" rows={2} className="min-h-[50px] flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none placeholder:text-muted-foreground" data-testid="input-assistant-question" /><button type="button" onClick={() => ask()} disabled={!question.trim() || agent.isPending} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground disabled:opacity-40" data-testid="button-submit-assistant"><ArrowUp size={18} /></button></div><div className="mt-2 flex items-center justify-between px-2 text-[10px] text-muted-foreground"><span>Enter to send · Shift + Enter for a new line</span><span>{analysis.posts.length} posts in context</span></div></div>
    </section>
    <aside className="space-y-4"><div className="rounded-2xl border border-card-border bg-sidebar p-5 text-sidebar-foreground"><div className="flex items-center gap-2 text-primary"><Lightbulb size={16} /><span className="font-mono-ui text-[10px] uppercase tracking-[.15em]">Try this first</span></div><p className="mt-4 font-display text-lg font-medium leading-snug">“Which format gives me the best return for the least effort?”</p><button type="button" onClick={() => ask('Which format gives me the best return for the least effort?')} className="mt-5 flex items-center gap-1 text-xs font-semibold text-primary hover:gap-2" data-testid="button-try-first">Ask this question <ArrowUp size={13} /></button></div><div className="rounded-2xl border border-card-border bg-card p-5"><div className="font-mono-ui text-[10px] uppercase tracking-[.15em] text-muted-foreground">Context loaded</div><div className="mt-4 space-y-3 text-xs"><div className="flex justify-between"><span className="text-muted-foreground">Account</span><strong>{analysis.accountName}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Period</span><strong>{analysis.period}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Posts</span><strong>{analysis.posts.length}</strong></div></div><div className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-[10px] text-muted-foreground"><Check size={13} className="text-accent" /> Every answer uses your data</div></div></aside>
  </div>;
}